#!/bin/bash
# Calendar Context Hook - Injects clear date/time before calendar operations
# Prevents day-of-week confusion when scheduling events

export TZ='America/Los_Angeles'

echo "## Calendar Date Reference (Pacific Time)"
echo ""
echo "**Current time:** $(date '+%H:%M %Z on %A, %B %d, %Y')"
echo ""
echo "Use these exact ISO dates for calendar API calls:"
echo ""
echo "| Day | Date | ISO (for API) |"
echo "|-----|------|---------------|"
echo "| Today | $(date '+%A, %b %d') | \`$(date '+%Y-%m-%d')\` |"
echo "| Tomorrow | $(date -d '+1 day' '+%A, %b %d') | \`$(date -d '+1 day' '+%Y-%m-%d')\` |"
echo "| $(date -d '+2 days' '+%A') | $(date -d '+2 days' '+%A, %b %d') | \`$(date -d '+2 days' '+%Y-%m-%d')\` |"
echo "| $(date -d '+3 days' '+%A') | $(date -d '+3 days' '+%A, %b %d') | \`$(date -d '+3 days' '+%Y-%m-%d')\` |"
echo "| $(date -d '+4 days' '+%A') | $(date -d '+4 days' '+%A, %b %d') | \`$(date -d '+4 days' '+%Y-%m-%d')\` |"
echo "| $(date -d '+5 days' '+%A') | $(date -d '+5 days' '+%A, %b %d') | \`$(date -d '+5 days' '+%Y-%m-%d')\` |"
echo "| $(date -d '+6 days' '+%A') | $(date -d '+6 days' '+%A, %b %d') | \`$(date -d '+6 days' '+%Y-%m-%d')\` |"
echo ""
echo "**IMPORTANT:** Always use timeZone: \"America/Los_Angeles\" in calendar API calls."
echo ""
echo "## Google Identity Rules"
echo "- Default ATLAS Google identity: claudiamooney00@gmail.com"
echo "- Default organizer calendar for bot-created events: claudiamooney00@gmail.com"
echo "- When James asks ATLAS to create an event, invite jamesmoon2@gmail.com unless he explicitly says not to."
echo "- If Emma should be invited, use lorzem15@gmail.com."
echo "- Treat jamesmoon2@gmail.com calendar access as read-only context unless James explicitly directs ATLAS to use a different calendar/account."
echo "- Outbound email must come from claudiamooney00@gmail.com unless James explicitly overrides that instruction."
echo ""
echo "## Key Contacts"
echo "| Name | Email | Use |"
echo "|------|-------|-----|"
echo "| ATLAS Bot | claudiamooney00@gmail.com | Gmail sender and organizer calendar |"
echo "| James | jamesmoon2@gmail.com | Default attendee for bot-created events |"
echo "| Emma | lorzem15@gmail.com | Use when James asks to invite Emma |"
